travis:
  secure:
    BINSTAR_TOKEN: HljAwmVmXPOq8/v5z8XyAorSf3sr9CkDQWSuY+ezH0AZomKMV+kBG9Qu9RJC7+Co87GuWiKRq2UvwiDr1N9+1Tzyxs/tsmgzq9gcrQwve2Mk1bzK3pgQLbZC+TCBg5iziUj9FPeDrVYu++jh84eAr3uoMwRaGCuiSc8Z5PlIhLpxMcyyUFy9ao524BaZzT+XtksSfm6T0CQG49XP3Ay1VIdt3Pk2digIWpGPEoSW+ay/XB6RY3sz98E3Bat09EN/N6ACUrj0olsWlocNYcvnph7IbtH4UX0CSVYkyAHKYz0fzrHRgWawnhcDnNOxQ/vztOJPnd3ms6s9fFjQL0cLQvjkoCvReqNt1/Ou7uzhd+d6PxADs2bDRe8x/YfFGOdK3M/CEyVR2a8/W/dGS0JI+aLUFQVO64Dnvvk1dM05TX3U7A02tzI8/hFH9OqaC0ubk/VSlohOs57CVzkyP64OsfR3LjgJxBSdtP1Tm3lJfRyI51i2oTPJhSEMdoGIBc0bXYocp1gFxJzXbkSjcoi6NjSRz3xDsuTvTxDMLH4jWyyOV4AjSsWNCSnOGE6HQFVVh9EbXp4oFsPzz1ibVUA0CzAPqgy4rn439khhFnAKkSNF4pJFX/RWjSEkpmR6MdlLOxR1kAVjl+ZneL9tl5v0Wma+EQZWoNuZdGJeC3P956A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
