travis:
  secure:
    BINSTAR_TOKEN: oz+a6Amj+XkA4f6JdiAhtRYUyAwfelJl+Z9udiVjpfdD4V2f3frVlIKmsm5rZcvHgC2r/BknNSd5ypn31Wj2VTKAI9J87qXZnZSO/fbSFc79sVdHA2he/Ys5g+ukPFH5qHtg+eiLHLVXZogcz1OJqa5mZRrNjvWbpWsl/Y9dt3F1QwSSmPeYc3CTHj9RXcUw2ttmYoMz8MtaR8oop2V+A8AjCT5VYHMEwjgVN7WXvPkpvbiYqy6BZrDq9M5/a+bj4c74fMP9+/yOY7RlKKHL/WPRlTeuObeS2biGRwVMpNshjWl0c1870hftkF+fkEtKpJ11lC2tBfdShGLfBFKJ/zIk0glzY+zxSVN6T6icHsP6HAn27hV5VuAYy4qh4qvK7/WZzHSki3bhZJJ56uzepaXaYr9MFRZhizSgNOg7uujnM55S0FgrUeu+fz+v4SWhIiUjtnUqBGgdTUr8PFDq6CE7A+CaqUaFNgmowb8PQMF51xnrUvfSqLqwb9lPmxvabFF9662b9kvV+YDBoIdmO9sOJPkED821/+muq3UnqpRf2/XfCPEqLSbzl3TdHy/m177Bd7Ufg45MUptX/amdnb7/NP6s6epLvbQNXtH99+VlNIXoG+JQV5QeCy8gQinFPUx5UbDF/Ba8bLiiJoBrdk3kx/fPL+CawXCMv3LuoP0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
